CREATE TABLE postingconfiguration (
    ID int not null AUTO_INCREMENT,
    CLIENTNAME varchar(255),
    POSTINGACCOUNTCONDITION varchar(255),
    POSTINGACCOUNTVALUE varchar(255),
    PRIMARY KEY (ID )
);


insert into postingconfiguration (ID,CLIENTNAME, POSTINGACCOUNTCONDITION,POSTINGACCOUNTVALUE) values (1,'UPSCALE','038CAESR0', 'FUND NAME');
insert into postingconfiguration (ID,CLIENTNAME, POSTINGACCOUNTCONDITION,POSTINGACCOUNTVALUE)  values (2,'UPSCALE','038CAESR01', 'FUND NAME1');
insert into postingconfiguration (ID,CLIENTNAME, POSTINGACCOUNTCONDITION,POSTINGACCOUNTVALUE)  values (3,'UPSCALE2','038CAESR01', 'NAME1');
insert into postingconfiguration (ID,CLIENTNAME, POSTINGACCOUNTCONDITION,POSTINGACCOUNTVALUE)  values  (4,'UPSCALE2','038CAESR0', 'NAME');
